---
title: "CRUK FGC analysis pipeline User Acceptance Testing (UAT)"
author: "Alex Kalinka"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    depth: 3
    highlight: tango
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
params:
  unpack_inputs: FALSE
  output_v1: FALSE
  output_v2: FALSE
  results_dir: FALSE
  lod_lfc: !r 0.8
  specificity: !r 0.99
  sensitivity: !r 0.78
---

# Setup

```{r setup}
set.seed(1)

if(is.logical(params$results_dir))
  stop("a valid path to the results directory must be provided in the list given to the 'params' argument")

if(!dir.exists(params$results_dir))
  stop("a valid path to the results directory must be provided in the list given to the 'params' argument")

if(is.logical(params$output_v1) || is.logical(params$output_v2))
  stop("Both 'output_v1' and 'output_v2' paths must be provided in the list given to the 'params' argument")

setwd(params$results_dir)
CWD <- getwd()

options(warn=-1)
suppressMessages(library(knitr))
suppressMessages(library(tidyr))
suppressMessages(library(magrittr))
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))

# Load bthin subset of genes with log2 fold-change signal added to their gRNAs.
lfc <- readRDS(file = file.path(params$output_v1,"bthin_lfc_rnorm.rds"))

## Common functions.
# Unpack the v1 data tarballs/zip archives to the current working directory.
unpack_inputs <- function(){
  ret <- NULL
  v1_files <- list.files(params$output_v1, full.names = T)
  for(file in v1_files){
    if(grepl("zip$",file)){
      system(paste("unzip",file))
    }
    if(grepl("tar.gz$",file)){
      fname <- gsub("^(.*?).tar.gz$","\\1",file)
      system(paste("gunzip -c",file,">",paste(fname,".tar",sep="")))
      system(paste("tar -xf",paste(fname,".tar",sep="")))
    }
  }
}

# Compare output file structure.
compare_analysis_files <- function(path_v1, path_v2){
  tryCatch({
    # Must change into dirs to remove upstream path differences.
    setwd(path_v1)
    v1_files <- list.files(path_v1, full.names = T, recursive = T)
    v1_files <- gsub("^.*?/(crisprn/.*)$","\\1",v1_files)
    # Must remove the 'GeneConnectivity' AZ-only interpretation files:
    v1_files <- v1_files[!grepl("GeneConnectivity",v1_files)]
    setwd(path_v2)
    v2_files <- list.files(path_v2, full.names = T, recursive = T)
    v2_files <- gsub("^.*?/(crisprn/.*)$","\\1",v2_files)
    # PathwayAnalysis seems to be new in v2:
    v2_files <- v2_files[!grepl("PathwayAnalysis",v2_files)]
    setwd(CWD)
    cat("Files private to v1:\n")
    print(setdiff(v1_files,v2_files))
    cat("Files private to v2:\n")
    print(setdiff(v2_files,v1_files))
  },
  error = function(e) stop(paste("unable to compare analysis output file structure:",e))
  )
}

# Compare counts.
compare_counts <- function(files_v1, files_v2){
  tryCatch({
    # Input orders can depend on exact order in json config.
    counts_v1 <- read.table(files_v1[grepl("combined_counts.txt",files_v1)],header=T,stringsAsFactors = F) %>%
      dplyr::arrange(sgRNA)
    counts_v1 <- counts_v1[,order(colnames(counts_v1))]
    counts_v2 <- read.table(files_v2[grepl("combined_counts.txt",files_v2)],header=T,stringsAsFactors = F) %>%
      dplyr::arrange(sgRNA)
    counts_v2 <- counts_v2[,order(colnames(counts_v2))]
  },
  error = function(e) stop(paste("unable to process counts files:",e))
  )
  return(all.equal(counts_v1, counts_v2))
}

# Compare Mageck gene summary output for Treatment vs Control.
compare_mageck <- function(files_v1, files_v2){
  tryCatch({
    # Ranks can vary when there are ties and so 'id' must also be re-arranged.
    mageck_v1 <- read.table(files_v1[grepl("Treatment_vs_Control.gene_summary.txt",files_v1)],
                            header=T,stringsAsFactors = F) %>%
      dplyr::arrange(id) %>%
      dplyr::select(-neg.rank, -pos.rank)
    mageck_v2 <- read.table(files_v2[grepl("Treatment_vs_Control.gene_summary.txt",files_v2)],
                            header=T,stringsAsFactors = F) %>%
      dplyr::arrange(id) %>%
      dplyr::select(-neg.rank, -pos.rank)
  },
  error = function(e) stop(paste("unable to process mageck files:",e))
  )
  return(all.equal(mageck_v1, mageck_v2))
}

# compare all.
compare_all <- function(path_v1, path_v2, type = "resistance", test_counts = T){
  if(!dir.exists(path_v1))
    stop(paste("unable to find v1 output:",path_v1))
  if(!dir.exists(path_v2))
    stop(paste("unable to find v2 output:",path_v2))
  tryCatch({
    cat("Analysis output file comparison:\n")
    print(compare_analysis_files(path_v1, path_v2))
    if(test_counts){
      cat("Count files identical:\n")
      print(compare_counts(list.files(path_v1,full.names = T,recursive = T),
                       list.files(path_v2,full.names = T,recursive = T)))
    }
    if(type == "resistance"){
      cat("Mageck Treatment vs Control identical:\n")
      print(compare_mageck(list.files(path_v1,full.names = T,recursive = T),
                       list.files(path_v2,full.names = T,recursive = T)))
    }
  },
  error = function(e) stop(paste("unable to compare data:",e))
  )
}

```


```{r}
if(params$unpack_inputs){
  # Unpack the inputs.
  tryCatch(unpack_inputs(),
           error = function(e) stop(paste("error unpacking v1 outputs:",e))
  )
}
```

# Concordance of pipeline outputs with v1

## 1. Multi-SLX input (Venetoclax sub-sampled FASTQs)

```{r}
# AP output structure from json:
# [general]project_name/[general]name/1/[comparisons]{crispr}type/[comparisons]name

cat("Day 7:")
path_v1 <- file.path(CWD,"fastq","crisprn","venetoclax_d7_vs_DMSO")
path_v2 <- file.path(params$output_v2,"public_data","public_PRJNA540211_MOLM13_Venetoclax_Yusa","1",
                     "crisprn","venetoclax_d7_vs_DMSO")

compare_all(path_v1, path_v2)

cat("Day 14:")
path_v1 <- file.path(CWD,"fastq","crisprn","venetoclax_d14_vs_DMSO")
path_v2 <- file.path(params$output_v2,"public_data","public_PRJNA540211_MOLM13_Venetoclax_Yusa",
                     "1","crisprn","venetoclax_d14_vs_DMSO")

compare_all(path_v1, path_v2)

```

## 2. HT29 (SLX-17741)

```{r}
path_v1 <- file.path(CWD,"ht29","combined_counts.txt")
path_v2 <- file.path(params$output_v2,"ht29-az","ht29-az_from_combinedcounts","1","crisprn",
                     "essentiality_test","counts","combined_counts.txt")

compare_counts(path_v1, path_v2)

```

## 3. Public data (Venetoclax)

### From sub-sampled FASTQs

```{r}
cat("Day 7:")
path_v1 <- file.path(CWD,"fastq","crisprn","venetoclax_d7_vs_DMSO")
path_v2 <- file.path(params$output_v2,"public_data","public_PRJNA540211_MOLM13_Venetoclax_Yusa_from_fastq",
                     "1","crisprn","venetoclax_d7_vs_DMSO")

compare_all(path_v1, path_v2)

cat("Day 14:")
path_v1 <- file.path(CWD,"fastq","crisprn","venetoclax_d14_vs_DMSO")
path_v2 <- file.path(params$output_v2,"public_data","public_PRJNA540211_MOLM13_Venetoclax_Yusa_from_fastq",
                     "1","crisprn","venetoclax_d14_vs_DMSO")

compare_all(path_v1, path_v2)

```

### From combined counts

```{r}
cat("Day 7:")
path_v1 <- file.path(CWD,"combined_counts","crisprn","venetoclax_d7_vs_DMSO")
path_v2 <- file.path(params$output_v2,"public_data","public_PRJNA540211_MOLM13_Venetoclax_Yusa_from_combinedcounts",
                     "1","crisprn","venetoclax_d7_vs_DMSO")

compare_all(path_v1, path_v2, test_counts = F)

cat("Day 14:")
path_v1 <- file.path(CWD,"combined_counts","crisprn","venetoclax_d14_vs_DMSO")
path_v2 <- file.path(params$output_v2,"public_data","public_PRJNA540211_MOLM13_Venetoclax_Yusa_from_combinedcounts",
                     "1","crisprn","venetoclax_d14_vs_DMSO")

compare_all(path_v1, path_v2, test_counts = F)

```


# Performance evaluation

## 1. Binomial-Thinned dataset

```{r}
# Limit of Detection (LOD) log2 fold change (for genes with a true signal).
# Genes with 0 < lfc < 0.8 will be ignored when calculating sens. and spec.
lod.lfc <- params$lod_lfc
path_mageck <- file.path(params$output_v2,"bthin","bthin_from_combinedcounts","1","crisprn",
                         "control_vs_treatment","mageck","Treatment_vs_Control.gene_summary.txt")

c903.mageck <- read.table(path_mageck, header=T, stringsAsFactors = F) %>%
  mutate(lfc_bthin = ifelse(id %in% names(lfc), lfc[match(id, names(lfc))], 0)) %>%
  rowwise() %>%
  mutate(sign.05 = (neg.fdr < 0.05 || pos.fdr < 0.05),
         sign.1 = (neg.fdr < 0.1 || pos.fdr < 0.1),
         ignore = (abs(lfc_bthin) > 0 && abs(lfc_bthin) < lod.lfc),
         true_neg = lfc_bthin==0,
         true_pos = abs(lfc_bthin)>0,
         false_pos = (sign.1 && lfc_bthin==0),
         false_neg = (!sign.1 && abs(lfc_bthin)>0)) %>%
  ungroup()

cat("10% FDR performance:")
kable(c903.mageck %>%
  filter(!ignore) %>%
  summarise(specificity = 1-sum(false_pos)/sum(true_neg),
            spec.pass = specificity > params$specificity,
            sensitivity = 1-sum(false_neg)/sum(true_pos),
            sens.pass = sensitivity > params$sensitivity
            )
)

cat("Comparing known logFC added as signal vs observed logFC taken from Mageck:")
ggplot(c903.mageck, aes(lfc_bthin,neg.lfc)) +
  geom_point() +
  geom_point(data = c903.mageck %>% filter(sign.1), aes(color="signif.")) +
  geom_abline(linetype="dashed") +
  xlab("Expected logFC") + ylab("Observed logFC") +
  ggtitle("logFC Observed vs Expected: Mageck hits at 10% FDR")

```


